cmake_minimum_required(VERSION 3.20)
project(LibraShogi LANGUAGES CXX)
option(LIBRA_BUILD_PYTHON "Build the pybind11 modules" ON)
option(LIBRA_BUILD_TESTS "Build the C++ tests" ON)
if(LIBRA_BUILD_PYTHON)
  find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)
  find_package(pybind11 CONFIG REQUIRED)
endif()
add_subdirectory(libra-sim)
add_subdirectory(libra-search)
